### ISSUE TITLE
Generate virtual-dom compatible AST

### ISSUE THREAD

**Issue by 0x00A** [voltraco/mineral#1]
Add an option to specify output as a virtual-dom compatible AST, instead of generating code -- similar to how `virtual-hyperscript` works. Tests are [`here`](https://github.com/Matt-Esch/virtual-dom/tree/master/virtual-hyperscript/test).

**Comment by juliangruber** [comment]
+1

**Comment by juliangruber** [comment]
> output as a virtual-dom compatible AST, instead of generating code

thinking about this a bit more, i realized we need to keep generating functions at all times since we wouldn't want to impose the overhead of parsing the template every single time. hyperscript gets away without caching as there's nothing to be parsed, but for mineral - which is very performance focused - we should keep the caching.

If we _do_ generate code for the virtual-dom option, we also need to let the user pass in the `virtual-dom/h` option, so we don't need to include in the template's preamble. What do you think about something like this?

```js
var tpl = min(code, { vdom: true });
var tree = tpl(locals, h);
```

**Comment by 0x00A** [comment]
Looks like [`morphdom`](https://github.com/patrick-steele-idem/morphdom) works great for this case.
